spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wdmrayzer_irl?useUnicode=true&characterEncoding=utf-8&&useSSL=false    
    username: root
    password: 123abc
    
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 500