  
server: 
  port: 8080
  
spring: 
  profiles: 
   active: db  #引入另外一个同路径下yml配置文件，该配置文件必须以application-开头

  redis:
    host: 192.168.1.65
    port: 6379
    database: 0
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 0
    
# debug: true

# 配置Mapper地址
mybatis:
  mapperLocations: classpath*:/mappers/**/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 配置log日志打印
# https://www.jianshu.com/p/1fa12b92d5c4
# https://www.cnblogs.com/bigdataZJ/p/springboot-log.html
logging:
  level:
    com.jmwdm: DEBUG
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n '     